### PR TITLE
Deploy to GitHub Pages automatically

### LINKED ISSUE #22: transfer from Wedos to DigitalOcean
- [ ] ditch the upload script (+ login.py)
- [ ] setup domain
- [ ] create private Git repository for the organization

### PR DESCRIPTION
**Pull request by filiptronicek**
Fixes #22

### CODE REVIEW

**Comment by filiptronicek** [comment]
@xiaoxiae could you or Honza add a CNAME record for `@` with the value of `meziklassociation.github.io` to the meziklasi.cz domain?

**Comment by yagarea** [comment]
I approve all changes made in this pull request. If @xiaoxiae finds it good too he can merge it right away.

**Comment by xiaoxiae** [comment]
Sure. Btw: pls fix Wedos DNS if you want this to work, I think I messed it up.

**Comment by yagarea** [comment]
image

Is there any progress ?

**Comment by yagarea** [comment]
DNS is (hopefully) fixed.

**Comment by filiptronicek** [comment]
Could we somehow get a TLS cert from Let's Encrypt or Cloudflare? 
image

**Comment by yagarea** [comment]
@filiptronicek 
I am voting for _Let's Encrypt_

**Pull request merged**
